create extension if not exists pgcrypto;

create table if not exists roles (
  id smallint primary key,
  name text not null unique check (name in ('Owner', 'Kasir'))
);

insert into roles (id, name) values (1, 'Owner'), (2, 'Kasir')
on conflict (id) do update set name = excluded.name;

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password_hash text not null,
  full_name text not null default '',
  role_id smallint not null references roles(id),
  active boolean not null default true,
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists refresh_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name_category text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists menus (
  id bigint generated by default as identity primary key,
  name_menu text not null,
  description text,
  price numeric(14,2) not null check (price >= 0),
  category_id bigint references categories(id),
  image_public_id text,
  image_url text not null default '',
  promo boolean not null default false,
  stock integer not null default 0 check (stock >= 0),
  promo_price numeric(14,2),
  promo_start date,
  promo_end date,
  is_deleted boolean not null default false,
  is_archive boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists shops (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  phone text,
  wifi_name text,
  wifi_password text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  client_order_id text not null unique,
  invoice_number text not null unique,
  customer text not null default '',
  total integer not null check (total > 0),
  total_amount numeric(14,2) not null check (total_amount >= 0),
  paid numeric(14,2),
  changes numeric(14,2) not null default 0,
  user_id uuid not null references users(id),
  payment_type text not null check (payment_type in ('cash', 'qris')),
  status text not null default 'completed',
  created_at timestamptz not null default now()
);

create table if not exists order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  menu_id bigint not null references menus(id),
  quantity integer not null check (quantity > 0),
  subtotal numeric(14,2) not null check (subtotal >= 0),
  price numeric(14,2) not null check (price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on orders (created_at desc);
create index if not exists order_items_order_id_idx on order_items (order_id);
create index if not exists menus_active_idx on menus (is_deleted, is_archive);
