export const themes: { [key: string] : {
    background: string,
    text: string,
    textSecondary: string,
    primary: string,
    secondary: string,
    border: string,
    card: string,
    danger: string,
    success: string,
  }} = {
    light: {
      background: '#FFF',
      text: '#000',
      textSecondary: '#6E6E73',
      primary: '#FFE9E1',
      secondary: '#9B51E0',
      border: '#E1E1E1',
      card: '#FFE9E1',
      danger: '#E74C3C',
      success: '#27AE60',
    },
    dark: {
      background: '#1A1D23',
      text: '#FFFFFF',
      textSecondary: '#B1B1B1',
      primary: '#64B5F6',
      secondary: '#8E24AA',
      border: '#333333',
      card: '#242526',
      danger: '#E74C3C',
      success: '#27AE60',
    },
  };