export const themes: { [key: string] : {
    background: string,
    text: string,
    textSecondary: string,
    primary: string,
    secondary: string,
    border: string,
    card: string,
    error: string,
    success: string,
  }} = {
    light: {
      background: '#F9F9F9',
      text: '#000',
      textSecondary: '#6E6E73',
      primary: '#4F1D03',
      secondary: '#FFE9E1',
      border: '#E1E1E1',
      card: '#FFF',
      error: '#E74C3C',
      success: '#27AE60',
    },
    dark: {
      background: '#1A1D23',
      text: '#FFF',
      textSecondary: '#B1B1B1',
      primary: '#FFE9E1',
      secondary: '#4F1D03',
      border: '#333333',
      card: '#000',
      error: '#E74C3C',
      success: '#27AE60',
    },
  };